<?php

use Detain\MyAdminSoftaculous\ArrayToXML;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-16 at 14:20:44.
 */
class ArrayToXMLTest extends TestCase
{
	/**
	 * @var ArrayToXML
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new ArrayToXML;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\ArrayToXML::toXML
	 * @todo   Implement testToXML().
	 */
	public function testToXML()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\ArrayToXML::toArray
	 * @todo   Implement testToArray().
	 */
	public function testToArray()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\ArrayToXML::isAssoc
	 * @todo   Implement testIsAssoc().
	 */
	public function testIsAssoc()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
