<?php

use Detain\MyAdminSoftaculous\SoftaculousNOC;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-16 at 14:20:22.
 */
class SoftaculousNOCTest extends TestCase
{
	/**
	 * @var SoftaculousNOC
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new SoftaculousNOC(getenv('SOFTACULOUS_USERNAME'), getenv('SOFTACULOUS_PASSWORD'));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::req
	 * @todo   Implement testReq().
	 */
	public function testReq()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::APImyadmin_unstringify
	 * @todo   Implement testAPImyadmin_unstringify().
	 */
	public function testAPImyadmin_unstringify()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::buy
	 * @todo   Implement testBuy().
	 */
	public function testBuy()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::refund
	 * @todo   Implement testRefund().
	 */
	public function testRefund()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::licenses
	 * @todo   Implement testLicenses().
	 */
	public function testLicenses()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::ipToKey
	 * @todo   Implement testIp_to_key().
	 */
	public function testIp_to_key()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::cancelWithRefund
	 * @todo   Implement testCancel_with_refund().
	 */
	public function testCancel_with_refund()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::cancel
	 * @todo   Implement testCancel().
	 */
	public function testCancel()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::refundAndCancel
	 * @todo   Implement testRefundAndCancel().
	 */
	public function testRefundAndCancel()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::editips
	 * @todo   Implement testEditips().
	 */
	public function testEditips()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::licenselogs
	 * @todo   Implement testLicenselogs().
	 */
	public function testLicenselogs()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::autorenewals
	 * @todo   Implement testAutorenewals().
	 */
	public function testAutorenewals()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::addautorenewal
	 * @todo   Implement testAddautorenewal().
	 */
	public function testAddautorenewal()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::removeautorenewal
	 * @todo   Implement testRemoveautorenewal().
	 */
	public function testRemoveautorenewal()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzoBuy
	 * @todo   Implement testWebuzo_buy().
	 */
	public function testWebuzo_buy()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzoRefund
	 * @todo   Implement testWebuzo_refund().
	 */
	public function testWebuzo_refund()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzoLicenses
	 * @todo   Implement testWebuzo_licenses().
	 */
	public function testWebuzo_licenses()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzoCancel
	 * @todo   Implement testWebuzo_cancel().
	 */
	public function testWebuzo_cancel()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzoRefundAndCancel
	 * @todo   Implement testWebuzoRefundAndCancel().
	 */
	public function testWebuzoRefundAndCancel()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzoEditips
	 * @todo   Implement testWebuzo_editips().
	 */
	public function testWebuzo_editips()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzoLicenselogs
	 * @todo   Implement testWebuzo_licenselogs().
	 */
	public function testWebuzo_licenselogs()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzoAutorenewals
	 * @todo   Implement testWebuzo_autorenewals().
	 */
	public function testWebuzo_autorenewals()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzoAddautorenewal
	 * @todo   Implement testWebuzo_addautorenewal().
	 */
	public function testWebuzo_addautorenewal()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzoRemoveautorenewal
	 * @todo   Implement testWebuzo_removeautorenewal().
	 */
	public function testWebuzo_removeautorenewal()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzotrial
	 * @todo   Implement testWebuzotrial().
	 */
	public function testWebuzotrial()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::virtBuy
	 * @todo   Implement testVirt_buy().
	 */
	public function testVirt_buy()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::virtRefund
	 * @todo   Implement testVirt_refund().
	 */
	public function testVirt_refund()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::virtLicenses
	 * @todo   Implement testVirt_licenses().
	 */
	public function testVirt_licenses()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::virtRemove
	 * @todo   Implement testVirt_remove().
	 */
	public function testVirt_remove()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::virtRefundAndCancel
	 * @todo   Implement testVirtRefundAndCancel().
	 */
	public function testVirtRefundAndCancel()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::virtEditips
	 * @todo   Implement testVirt_editips().
	 */
	public function testVirt_editips()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::virtLicenselogs
	 * @todo   Implement testVirt_licenselogs().
	 */
	public function testVirt_licenselogs()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::virtRenewals
	 * @todo   Implement testVirt_renewals().
	 */
	public function testVirt_renewals()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::virtAddautorenewal
	 * @todo   Implement testVirt_addautorenewal().
	 */
	public function testVirt_addautorenewal()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::virtRemoveautorenewal
	 * @todo   Implement testVirt_removeautorenewal().
	 */
	public function testVirt_removeautorenewal()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::sitemushBuy
	 * @todo   Implement testSitemush_buy().
	 */
	public function testSitemush_buy()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::sitemushRefund
	 * @todo   Implement testSitemush_refund().
	 */
	public function testSitemush_refund()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::sitemushLicenses
	 * @todo   Implement testSitemush_licenses().
	 */
	public function testSitemush_licenses()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::sitemushRemove
	 * @todo   Implement testSitemush_remove().
	 */
	public function testSitemush_remove()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::sitemushRefundAndCancel
	 * @todo   Implement testSitemushRefundAndCancel().
	 */
	public function testSitemushRefundAndCancel()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::sitemushEditips
	 * @todo   Implement testSitemush_editips().
	 */
	public function testSitemush_editips()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::sitemushLicenselogs
	 * @todo   Implement testSitemush_licenselogs().
	 */
	public function testSitemush_licenselogs()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::sitemushRenewals
	 * @todo   Implement testSitemush_renewals().
	 */
	public function testSitemush_renewals()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::sitemushAddautorenewal
	 * @todo   Implement testSitemush_addautorenewal().
	 */
	public function testSitemush_addautorenewal()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::sitemushRemoveautorenewal
	 * @todo   Implement testSitemush_removeautorenewal().
	 */
	public function testSitemush_removeautorenewal()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::invoicedetails
	 * @todo   Implement testInvoicedetails().
	 */
	public function testInvoicedetails()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::r
	 * @todo   Implement testR().
	 */
	public function testR()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
