<?php

use Detain\MyAdminSoftaculous\SOFT_NOC;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-16 at 14:20:22.
 */
class SOFT_NOCTest extends TestCase
{
	/**
	 * @var SOFT_NOC
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new SOFT_NOC(getenv('SOFTACULOUS_USERNAME'), getenv('SOFTACULOUS_PASSWORD'));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::req
	 * @todo   Implement testReq().
	 */
	public function testReq()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::APImyadmin_unstringify
	 * @todo   Implement testAPImyadmin_unstringify().
	 */
	public function testAPImyadmin_unstringify()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::buy
	 * @todo   Implement testBuy().
	 */
	public function testBuy()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::refund
	 * @todo   Implement testRefund().
	 */
	public function testRefund()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::licenses
	 * @todo   Implement testLicenses().
	 */
	public function testLicenses()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::ipToKey
	 * @todo   Implement testIp_to_key().
	 */
	public function testIp_to_key()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::cancelWithRefund
	 * @todo   Implement testCancel_with_refund().
	 */
	public function testCancel_with_refund()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::cancel
	 * @todo   Implement testCancel().
	 */
	public function testCancel()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::refundAndCancel
	 * @todo   Implement testRefundAndCancel().
	 */
	public function testRefundAndCancel()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::editips
	 * @todo   Implement testEditips().
	 */
	public function testEditips()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::licenselogs
	 * @todo   Implement testLicenselogs().
	 */
	public function testLicenselogs()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::autorenewals
	 * @todo   Implement testAutorenewals().
	 */
	public function testAutorenewals()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::addautorenewal
	 * @todo   Implement testAddautorenewal().
	 */
	public function testAddautorenewal()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::removeautorenewal
	 * @todo   Implement testRemoveautorenewal().
	 */
	public function testRemoveautorenewal()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::webuzoBuy
	 * @todo   Implement testWebuzo_buy().
	 */
	public function testWebuzo_buy()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::webuzoRefund
	 * @todo   Implement testWebuzo_refund().
	 */
	public function testWebuzo_refund()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::webuzoLicenses
	 * @todo   Implement testWebuzo_licenses().
	 */
	public function testWebuzo_licenses()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::webuzoCancel
	 * @todo   Implement testWebuzo_cancel().
	 */
	public function testWebuzo_cancel()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::webuzoRefundAndCancel
	 * @todo   Implement testWebuzoRefundAndCancel().
	 */
	public function testWebuzoRefundAndCancel()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::webuzoEditips
	 * @todo   Implement testWebuzo_editips().
	 */
	public function testWebuzo_editips()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::webuzoLicenselogs
	 * @todo   Implement testWebuzo_licenselogs().
	 */
	public function testWebuzo_licenselogs()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::webuzoAutorenewals
	 * @todo   Implement testWebuzo_autorenewals().
	 */
	public function testWebuzo_autorenewals()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::webuzoAddautorenewal
	 * @todo   Implement testWebuzo_addautorenewal().
	 */
	public function testWebuzo_addautorenewal()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::webuzoRemoveautorenewal
	 * @todo   Implement testWebuzo_removeautorenewal().
	 */
	public function testWebuzo_removeautorenewal()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::webuzotrial
	 * @todo   Implement testWebuzotrial().
	 */
	public function testWebuzotrial()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::virtBuy
	 * @todo   Implement testVirt_buy().
	 */
	public function testVirt_buy()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::virtRefund
	 * @todo   Implement testVirt_refund().
	 */
	public function testVirt_refund()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::virtLicenses
	 * @todo   Implement testVirt_licenses().
	 */
	public function testVirt_licenses()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::virtRemove
	 * @todo   Implement testVirt_remove().
	 */
	public function testVirt_remove()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::virtRefundAndCancel
	 * @todo   Implement testVirtRefundAndCancel().
	 */
	public function testVirtRefundAndCancel()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::virtEditips
	 * @todo   Implement testVirt_editips().
	 */
	public function testVirt_editips()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::virtLicenselogs
	 * @todo   Implement testVirt_licenselogs().
	 */
	public function testVirt_licenselogs()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::virtRenewals
	 * @todo   Implement testVirt_renewals().
	 */
	public function testVirt_renewals()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::virtAddautorenewal
	 * @todo   Implement testVirt_addautorenewal().
	 */
	public function testVirt_addautorenewal()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::virtRemoveautorenewal
	 * @todo   Implement testVirt_removeautorenewal().
	 */
	public function testVirt_removeautorenewal()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::sitemushBuy
	 * @todo   Implement testSitemush_buy().
	 */
	public function testSitemush_buy()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::sitemushRefund
	 * @todo   Implement testSitemush_refund().
	 */
	public function testSitemush_refund()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::sitemushLicenses
	 * @todo   Implement testSitemush_licenses().
	 */
	public function testSitemush_licenses()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::sitemushRemove
	 * @todo   Implement testSitemush_remove().
	 */
	public function testSitemush_remove()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::sitemushRefundAndCancel
	 * @todo   Implement testSitemushRefundAndCancel().
	 */
	public function testSitemushRefundAndCancel()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::sitemushEditips
	 * @todo   Implement testSitemush_editips().
	 */
	public function testSitemush_editips()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::sitemushLicenselogs
	 * @todo   Implement testSitemush_licenselogs().
	 */
	public function testSitemush_licenselogs()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::sitemushRenewals
	 * @todo   Implement testSitemush_renewals().
	 */
	public function testSitemush_renewals()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::sitemushAddautorenewal
	 * @todo   Implement testSitemush_addautorenewal().
	 */
	public function testSitemush_addautorenewal()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::sitemushRemoveautorenewal
	 * @todo   Implement testSitemush_removeautorenewal().
	 */
	public function testSitemush_removeautorenewal()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::invoicedetails
	 * @todo   Implement testInvoicedetails().
	 */
	public function testInvoicedetails()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminSoftaculous\SOFT_NOC::r
	 * @todo   Implement testR().
	 */
	public function testR()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
