<?php

use Detain\MyAdminSoftaculous\SoftaculousNOC;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-26 at 08:06:42.
 */
class SoftaculousNOCTest extends TestCase
{
    /**
     * @var SoftaculousNOC
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        if (file_exists(__DIR__.'/.env')) {
            $dotenv = new Dotenv\Dotenv(__DIR__);
            $dotenv->load();
        }
        $this->object = new SoftaculousNOC(getenv('SOFTACULOUS_USERNAME'), getenv('SOFTACULOUS_PASSWORD'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::req
     * @todo   Implement testReq().
     */
    public function testReq()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::buy
     * @todo   Implement testBuy().
     */
    public function testBuy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::refund
     * @todo   Implement testRefund().
     */
    public function testRefund()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::licenses
     * @todo   Implement testLicenses().
     */
    public function testLicenses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::ipToKey
     * @todo   Implement testIpToKey().
     */
    public function testIpToKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::cancelWithRefund
     * @todo   Implement testCancelWithRefund().
     */
    public function testCancelWithRefund()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::cancel
     * @todo   Implement testCancel().
     */
    public function testCancel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::refundAndCancel
     * @todo   Implement testRefundAndCancel().
     */
    public function testRefundAndCancel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::editips
     * @todo   Implement testEditips().
     */
    public function testEditips()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::licenselogs
     * @todo   Implement testLicenselogs().
     */
    public function testLicenselogs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::autorenewals
     * @todo   Implement testAutorenewals().
     */
    public function testAutorenewals()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::addautorenewal
     * @todo   Implement testAddautorenewal().
     */
    public function testAddautorenewal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::removeautorenewal
     * @todo   Implement testRemoveautorenewal().
     */
    public function testRemoveautorenewal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzoBuy
     * @todo   Implement testWebuzoBuy().
     */
    public function testWebuzoBuy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzoRefund
     * @todo   Implement testWebuzoRefund().
     */
    public function testWebuzoRefund()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzoLicenses
     * @todo   Implement testWebuzoLicenses().
     */
    public function testWebuzoLicenses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzoCancel
     * @todo   Implement testWebuzoCancel().
     */
    public function testWebuzoCancel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzoRefundAndCancel
     * @todo   Implement testWebuzoRefundAndCancel().
     */
    public function testWebuzoRefundAndCancel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzoEditips
     * @todo   Implement testWebuzoEditips().
     */
    public function testWebuzoEditips()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzoLicenselogs
     * @todo   Implement testWebuzoLicenselogs().
     */
    public function testWebuzoLicenselogs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzoAutorenewals
     * @todo   Implement testWebuzoAutorenewals().
     */
    public function testWebuzoAutorenewals()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzoAddautorenewal
     * @todo   Implement testWebuzoAddautorenewal().
     */
    public function testWebuzoAddautorenewal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzoRemoveautorenewal
     * @todo   Implement testWebuzoRemoveautorenewal().
     */
    public function testWebuzoRemoveautorenewal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::webuzotrial
     * @todo   Implement testWebuzotrial().
     */
    public function testWebuzotrial()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::virtBuy
     * @todo   Implement testVirtBuy().
     */
    public function testVirtBuy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::virtRefund
     * @todo   Implement testVirtRefund().
     */
    public function testVirtRefund()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::virtLicenses
     * @todo   Implement testVirtLicenses().
     */
    public function testVirtLicenses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::virtRemove
     * @todo   Implement testVirtRemove().
     */
    public function testVirtRemove()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::virtRefundAndCancel
     * @todo   Implement testVirtRefundAndCancel().
     */
    public function testVirtRefundAndCancel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::virtEditips
     * @todo   Implement testVirtEditips().
     */
    public function testVirtEditips()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::virtLicenselogs
     * @todo   Implement testVirtLicenselogs().
     */
    public function testVirtLicenselogs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::virtRenewals
     * @todo   Implement testVirtRenewals().
     */
    public function testVirtRenewals()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::virtAddautorenewal
     * @todo   Implement testVirtAddautorenewal().
     */
    public function testVirtAddautorenewal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::virtRemoveautorenewal
     * @todo   Implement testVirtRemoveautorenewal().
     */
    public function testVirtRemoveautorenewal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::sitemushBuy
     * @todo   Implement testSitemushBuy().
     */
    public function testSitemushBuy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::sitemushRefund
     * @todo   Implement testSitemushRefund().
     */
    public function testSitemushRefund()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::sitemushLicenses
     * @todo   Implement testSitemushLicenses().
     */
    public function testSitemushLicenses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::sitemushRemove
     * @todo   Implement testSitemushRemove().
     */
    public function testSitemushRemove()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::sitemushRefundAndCancel
     * @todo   Implement testSitemushRefundAndCancel().
     */
    public function testSitemushRefundAndCancel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::sitemushEditips
     * @todo   Implement testSitemushEditips().
     */
    public function testSitemushEditips()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::sitemushLicenselogs
     * @todo   Implement testSitemushLicenselogs().
     */
    public function testSitemushLicenselogs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::sitemushRenewals
     * @todo   Implement testSitemushRenewals().
     */
    public function testSitemushRenewals()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::sitemushAddautorenewal
     * @todo   Implement testSitemushAddautorenewal().
     */
    public function testSitemushAddautorenewal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::sitemushRemoveautorenewal
     * @todo   Implement testSitemushRemoveautorenewal().
     */
    public function testSitemushRemoveautorenewal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::invoicedetails
     * @todo   Implement testInvoicedetails().
     */
    public function testInvoicedetails()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminSoftaculous\SoftaculousNOC::displayResponse
     * @todo   Implement testDisplayResponse().
     */
    public function testDisplayResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
